### ISSUE TITLE
Register DIPLOID variant calling workflow with BRC Analytics

### ISSUE THREAD

**Issue by NoopDog** [galaxyproject/brc-analytics#304]
#### Need 
The initial set of workflows is configured [here](https://github.com/galaxyproject/brc-analytics/blob/main/catalog/source/workflows.yml). 

This setup now supports matching the ploidy of organisms with the ploidy of the workflow.
Ploidy for organisms is configured [here](https://github.com/galaxyproject/brc-analytics/blob/main/catalog/source/organisms.yml).

```
workflows:
  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/chipseq-pe/main/versions/v0.12"
    categories:
      - "REGULATION"
    ploidy: "ANY"
    workflow_name: "ChIPseq_PE"
    workflow_description: "This workflow takes as input a collection of paired fastqs. Remove adapters with cutadapt, map pairs with bowtie2. Keep MAPQ30 and concordant pairs. MACS2 for paired bam."

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/rnaseq-pe/main/versions/v0.9"
    categories:
      - "TRANSCRIPTOMICS"
    ploidy: "ANY"
    workflow_name: "RNAseq_PE"
    workflow_description: "This workflow takes as input a list of paired-end fastqs. Adapters and bad quality bases are removed with cutadapt. Reads are mapped with STAR with ENCODE parameters and genes are counted simultaneously as well as normalized coverage (per million mapped reads) on uniquely mapped reads. The counts are reprocessed to be similar to HTSeq-count output. FPKM are computed with cufflinks and/or with StringTie. The unstranded normalized coverage is computed with bedtools."

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/haploid-variant-calling-wgs-pe/main/versions/v0.1"
    categories:
      - "VARIANT_CALLING"
    ploidy: "HAPLOID"
    workflow_name: "Paired end variant calling in haploid system"
    workflow_description: "Workflow for variant analysis against a reference genome in GenBank format"
```

Now that ploidy matching is configured, we only show the variant calling workflow for HAPLOID organisms.

#### Approach

1. If we have a variant calling workflow for DIPLOID organisms, it would be great to configure it. This assumes the [getWorkflowLandingURL](https://github.com/galaxyproject/brc-analytics/blob/1004775a5c54c58f8ed78ccdfbfbb1b547fb926c/app/utils/galaxy-api.ts#L33) works appropriately for the DIPLOID worklow. See:

```
function getWorkflowLandingsRequestState(
  workflowId: string,
  referenceGenome: string,
  geneModelUrl: string | null
): WorkflowLandingsBodyRequestState {
  if (workflowId === WORKFLOW_ID_VARIANT_CALLING && geneModelUrl) {
    return {
      "Annotation GTF": { ext: "gtf.gz", src: "url", url: geneModelUrl },
      "Genome fasta": {
        ext: "fasta.gz",
        src: "url",
        url: buildFastaUrl(referenceGenome),
      },
    };
  }
  return { reference_genome: referenceGenome };
}
```

If not we will need to work with @mvdbeek first to update this method.
