### ISSUE TITLE
Review and prioritize additional workflows to be added to the BRC Site

### ISSUE THREAD

**Issue by NoopDog** [galaxyproject/brc-analytics#322]
#### Need

Currently, the BRC site has three workflows, but the IWS has 100 or so. We have a prioritized list of the [first eight workflows](https://github.com/galaxyproject/brc-analytics/blob/11366c6d9b2a47cfef397507db21015ef295b3ea/files/source/galaxy_workflows.yml) to add to BRC; however, we need to understand if these workflows require any additional parameters to be sent.

The initial eight are (tho the structure has changd for the YAML)

```
workflows:
  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/chipseq-pe/main/versions/v0.12"
    type: "REGULATION"
    description: "Workflows for the analysis of ChIP-seq, ATAC-Seq, and beyond."
    ploidy: "any"

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/chipseq-sr/main/versions/v0.12"
    type: "REGULATION"
    description: "Workflows for the analysis of ChIP-seq, ATAC-Seq, and beyond."
    ploidy: "any"

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/rnaseq-pe/main/versions/v1.2"
    type: "TRANSCRIPTOMICS"
    description: "Analyze bulk or single-cell RNA seq data using a variety of approaches."
    ploidy: "any"

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/rnaseq-sr/main/versions/v1.2"
    type: "TRANSCRIPTOMICS"
    description: "Analyze bulk or single-cell RNA seq data using a variety of approaches."
    ploidy: "any"

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/haploid-variant-calling-wgs-pe/main/versions/v0.1"
    type: "VARIANT_CALLING"
    description: "Identify nucleotide polymorphisms and short indels from Illumina and Element data."
    ploidy: "haploid"

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/generic-variant-calling-wgs-pe/main/versions/v0.1.1"
    type: "VARIANT_CALLING"
    description: "Identify nucleotide polymorphisms and short indels from Illumina and Element data."
    ploidy: "haploid"

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/assembly-with-flye/main/versions/v0.2"
    type: "ASSEMBLY"
    description: "Assemble prokaryotic and eukaryotic genomes sequenced with a variety of technologies."
    ploidy: "any"

  - trs_id: "https://dockstore.org/api/ga4gh/trs/v2/tools/#workflow/github.com/iwc-workflows/bacterial-genome-assembly/main/versions/v1.1.5"
    type: "ASSEMBLY"
    description: "Assemble prokaryotic and eukaryotic genomes sequenced with a variety of technologies."
    ploidy: "any"
```

#### Request 

- [ ] 1. Determine if additional configuration parameters are needed for each of the eight prioritized workflows. 
- [ ] 2. Update the configuration in BRC Analytics for any of the initial eight prioritized workflows that can be added now.
- [ ] 3. List the parameters for any of the original eight workflows that need to be added to BRC so we can call them.
- [ ] 4. Do the same for the remaining workflows according to their priority.

We have a list of the required parameters [here](https://gist.github.com/mvdbeek/b53d73a5fcba2677b0706bcd7ab10704) however, it is not clear which of those parameters need to be populated on the initial call to Galaxy.
